# Schema for the configuration files of the Rate converter module.
exchange_rate_converter.settings:
  type: config_object
  label: 'Rate converter settings'
  mapping:
    example:
      type: string
      label: 'Example'
